### ISSUE TITLE
Support for GPT4

### ISSUE THREAD

**Issue by moochookaboo** [freistli/rootbot#14]
Appreciate you making this utility!

I am trying to get the bot to work with gpt-4-32k deployment. I am able to get the installation to the point where I can message the bot on teams and it will reply with the Root Bot V.03102023 card. However, the bot doesn't respond back to any other messages. 

Should GPT4 work natively? Or any suggestions on how I can get GPT4 to work? 

Thank you in advance!

**Comment by freistli** [comment]
Thank you @moochookaboo!

Currently the Azure OpenAI ChatGPT (Azure Function part https://github.com/freistli/chatgpt-api/blob/main/demos/demo-azure-chatgpt-function/azureopenai/index.ts ) in the project uses Completion API instead of Chat API, thus GPT 3.5 only.

To use GTP 4, you can modify the TS code https://github.com/freistli/chatgpt-api/blob/main/src/azure-chatgpt-api.ts to use Chat API, generate a new npm (AzureChatGPTAPI), and let the Azure Function part to use it. 

Or you can use Teams AI Library to build your bot directly, which will support GPT4 - https://github.com/microsoft/teams-ai
